---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaces-configurations
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/ArgoCD-ACM-Refactor/acm-all-managed-cluster-config.git
      revision: v1.0.0
      files:
      - path: "**/cluster.json"
  template:
    metadata:
      name: '{{cluster.name}}-namespaces'
    spec:
      project: default
      source:
        repoURL: https://github.com/ArgoCD-ACM-Refactor/acm-managed-clusters-paas-configurations.git
        targetRevision: main
        path: global-configurations/namespaces/overlays/{{cluster.name}}
      destination:
        server: '{{cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
